import { useContext, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import useAuth from '../../hooks/useAuth.js';
import { NotificationContext } from '../../context/NotificationContext.jsx';
import { userService } from '../../services/userService.js';
import './SecurityPage.css';

const requirements = [['length', 'At least 8 characters'], ['uppercase', 'One uppercase letter'], ['lowercase', 'One lowercase letter'], ['number', 'One number'], ['special', 'One special character']];
const Icon = ({ children, size = 19 }) => <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{children}</svg>;
const FieldError = ({ children }) => children ? <span className="err-msg">{children}</span> : null;

export function PageHeader() { return <header className="security-page-header"><h1>Security Settings</h1><p>Manage your account security and login credentials.</p></header>; }

export function EmailCard({ user, onUserUpdate }) {
  const { notify } = useContext(NotificationContext); const [expanded, setExpanded] = useState(false); const [newEmail, setNewEmail] = useState(''); const [code, setCode] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const close = () => { setExpanded(false); setNewEmail(''); setCode(''); setError(''); };
  const sendCode = () => { if (!/\S+@\S+\.\S+/.test(newEmail)) { setError('Enter a valid new email address first.'); return; } setError(''); notify({ message: 'Verification code requested', type: 'success' }); };
  const updateEmail = async (event) => { event.preventDefault(); if (!/\S+@\S+\.\S+/.test(newEmail)) { setError('Enter a valid new email address.'); return; } if (!code.trim()) { setError('Enter the verification code.'); return; } setLoading(true); setError(''); try { const updated = await userService.updateProfile({ name: user?.name || '', email: newEmail, role: user?.role || 'CREATOR' }); onUserUpdate(updated); notify({ message: 'Email updated successfully', type: 'success' }); close(); } catch (err) { setError(err.response?.data?.message || 'Unable to update your email. Please try again.'); notify({ message: 'Email update failed', type: 'error' }); } finally { setLoading(false); } };
  return <section className="security-card" aria-labelledby="email-information-title"><div className="security-card-heading"><div className="security-card-icon"><Icon><path d="M3 5h18v14H3z"/><path d="m3 7 9 6 9-6"/></Icon></div><div><h2 id="email-information-title">Email Information</h2><p>Your email is used to sign in and receive account updates.</p></div></div><div className="security-email-row"><div className="security-readonly"><span>Current Email</span><strong>{user?.email || 'Not available'}</strong></div><button type="button" className="security-secondary-button" onClick={() => setExpanded(!expanded)}>{expanded ? 'Close' : 'Change Email'}</button></div><div className={`email-expand ${expanded ? 'is-open' : ''}`} aria-hidden={!expanded}>{expanded && <form onSubmit={updateEmail} className="security-email-form"><div className="security-fields-grid"><div className="form-group"><label className="form-label">Current Email</label><input className="f-input" value={user?.email || ''} readOnly /></div><div className="form-group"><label className="form-label" htmlFor="security-new-email">New Email</label><input id="security-new-email" className="f-input" type="email" placeholder="name@example.com" value={newEmail} onChange={(e) => setNewEmail(e.target.value)} disabled={loading} /></div></div><div className="security-code-row"><div className="form-group"><label className="form-label" htmlFor="security-email-code">Verification Code</label><input id="security-email-code" className="f-input" inputMode="numeric" placeholder="Enter verification code" value={code} onChange={(e) => setCode(e.target.value)} disabled={loading} /></div><button type="button" className="security-text-button" onClick={sendCode} disabled={loading}>Send Code</button></div><FieldError>{error}</FieldError><div className="security-form-actions"><button type="button" className="btn-back" onClick={close} disabled={loading}>Cancel</button><button type="submit" className="security-primary-button" disabled={loading}>{loading ? <span className="spin" /> : 'Update Email'}</button></div></form>}</div></section>;
}

function PasswordInput({ id, label, value, onChange, error, disabled, placeholder }) { const [shown, setShown] = useState(false); return <div className="form-group"><label className="form-label" htmlFor={id}>{label}</label><div className="security-password-input"><input id={id} className={`f-input ${error ? 'err' : ''}`} type={shown ? 'text' : 'password'} value={value} onChange={onChange} disabled={disabled} placeholder={placeholder} autoComplete={id === 'security-current-password' ? 'current-password' : 'new-password'} /><button type="button" aria-label={`${shown ? 'Hide' : 'Show'} ${label}`} onClick={() => setShown(!shown)}><Icon size={18}>{shown ? <><path d="m3 3 18 18"/><path d="M10.6 10.6a2 2 0 0 0 2.8 2.8"/><path d="M9.9 4.2A10.8 10.8 0 0 1 12 4c5 0 8.3 4.1 9 8-.2 1.1-.7 2.2-1.4 3.2"/><path d="M6.6 6.6C4.6 8 3.4 10.1 3 12c.7 3.9 4 8 9 8 1.4 0 2.6-.3 3.7-.8"/></> : <><path d="M3 12s3.3-8 9-8 9 8 9 8-3.3 8-9 8-9-8-9-8Z"/><circle cx="12" cy="12" r="3"/></>}</Icon></button></div><FieldError>{error}</FieldError></div>; }

export function PasswordCard({ password, setPassword }) {
  const { notify } = useContext(NotificationContext); const [loading, setLoading] = useState(false); const [errors, setErrors] = useState({}); const [apiError, setApiError] = useState(''); const checks = useMemo(() => ({ length: password.newPassword.length >= 8, uppercase: /[A-Z]/.test(password.newPassword), lowercase: /[a-z]/.test(password.newPassword), number: /\d/.test(password.newPassword), special: /[^A-Za-z0-9]/.test(password.newPassword) }), [password.newPassword]); const update = (key) => (event) => setPassword({ ...password, [key]: event.target.value });
  const submit = async (event) => { event.preventDefault(); setApiError(''); const next = {}; if (!password.currentPassword) next.currentPassword = 'Current password is required.'; if (!checks.length) next.newPassword = 'Password must be at least 8 characters.'; else if (!Object.values(checks).every(Boolean)) next.newPassword = 'Password does not meet all requirements.'; if (password.newPassword !== password.confirmPassword) next.confirmPassword = 'Passwords do not match.'; if (password.currentPassword === password.newPassword && password.currentPassword) next.newPassword = 'Choose a password different from your current one.'; setErrors(next); if (Object.keys(next).length) return; setLoading(true); try { await userService.changePassword(password); notify({ message: 'Password updated successfully', type: 'success' }); setPassword({ currentPassword: '', newPassword: '', confirmPassword: '' }); } catch (err) { setApiError(err.response?.data?.message || 'Password update failed. Verify your current password.'); notify({ message: 'Password change failed', type: 'error' }); } finally { setLoading(false); } };
  return <section className="security-card" aria-labelledby="password-title"><div className="security-card-heading"><div className="security-card-icon"><Icon><rect x="4" y="10" width="16" height="10" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/><path d="M12 14v2"/></Icon></div><div><h2 id="password-title">Password</h2><p>Choose a strong, unique password to protect your account.</p></div></div>{apiError && <div className="security-api-error">{apiError}</div>}<form onSubmit={submit} className="security-password-layout"><div><PasswordInput id="security-current-password" label="Current Password" value={password.currentPassword} onChange={update('currentPassword')} error={errors.currentPassword} disabled={loading} placeholder="Enter current password"/><PasswordInput id="security-new-password" label="New Password" value={password.newPassword} onChange={update('newPassword')} error={errors.newPassword} disabled={loading} placeholder="Create a new password"/><PasswordInput id="security-confirm-password" label="Confirm Password" value={password.confirmPassword} onChange={update('confirmPassword')} error={errors.confirmPassword} disabled={loading} placeholder="Confirm your new password"/></div><div className="security-requirements"><h3>Password Requirements</h3>{requirements.map(([key, text]) => <div className={checks[key] ? 'met' : ''} key={key}><span>{checks[key] ? '✓' : '•'}</span>{text}</div>)}</div><button type="submit" className="security-primary-button security-password-submit" disabled={loading}>{loading ? <span className="spin" /> : 'Update Password'}</button></form></section>;
}

export function DangerZoneCard({ onLogout }) { return <section className="security-card security-danger-card"><div className="security-card-heading"><div className="security-card-icon security-danger-icon"><Icon><path d="M10 17l5-5-5-5"/><path d="M15 12H3"/><path d="M14 4h4a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2h-4"/></Icon></div><div><h2>Danger Zone</h2><p>Actions that end your current session.</p></div></div><div className="security-danger-action"><div><h3>Logout</h3><p>You will need to sign in again on this device.</p></div><button type="button" className="security-logout-button" onClick={onLogout}>Logout</button></div></section>; }
export function SecurityScoreCard({ password }) { const score = [password.newPassword.length >= 8, /[A-Z]/.test(password.newPassword), /[a-z]/.test(password.newPassword), /\d/.test(password.newPassword), /[^A-Za-z0-9]/.test(password.newPassword)].filter(Boolean).length; const label = score >= 5 ? 'Strong' : score >= 3 ? 'Medium' : 'Weak'; return <aside className="security-side-card security-score-card"><div className="security-side-title"><Icon><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/><path d="m9 12 2 2 4-4"/></Icon><span>Security Score</span></div><strong className={`security-score ${label.toLowerCase()}`}>{label}</strong><div className="security-score-meter" aria-label={`${label} security score`}><span style={{ width: `${Math.max(20, score * 20)}%` }} /></div><p>{password.newPassword ? 'Based on your new password.' : 'Create a strong password to improve your score.'}</p></aside>; }
export function SecurityTipsCard() { return <aside className="security-side-card"><div className="security-side-title"><Icon><path d="M9 18h6"/><path d="M10 22h4"/><path d="M8.5 14.5A6 6 0 1 1 15.5 14.5c-.7.6-1.2 1.2-1.3 2H9.8c-.1-.8-.6-1.4-1.3-2Z"/></Icon><span>Security Tips</span></div><ul className="security-tips"><li>Use a strong, unique password.</li><li>Keep your recovery email updated.</li><li>Enable 2FA when it becomes available.</li></ul></aside>; }
export function TwoFactorCard() { return <aside className="security-side-card security-two-factor"><span>Coming Soon</span><h2>Two-Factor Authentication</h2><p>Add another layer of protection with a verification app.</p></aside>; }
export function LogoutDialog({ open, onClose, onConfirm }) { if (!open) return null; return <div className="security-dialog-backdrop" role="presentation"><div className="security-dialog" role="dialog" aria-modal="true" aria-labelledby="logout-dialog-title"><div className="security-dialog-icon"><Icon size={22}><path d="M10 17l5-5-5-5"/><path d="M15 12H3"/><path d="M14 4h4a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2h-4"/></Icon></div><h2 id="logout-dialog-title">Logout?</h2><p>You will need to sign in again.</p><div className="security-dialog-actions"><button type="button" className="btn-back" onClick={onClose}>Cancel</button><button type="button" className="security-logout-button" onClick={onConfirm}>Logout</button></div></div></div>; }

export default function SecurityPage() { const { user, updateUser, logout } = useAuth(); const { notify } = useContext(NotificationContext); const navigate = useNavigate(); const [password, setPassword] = useState({ currentPassword: '', newPassword: '', confirmPassword: '' }); const [logoutOpen, setLogoutOpen] = useState(false); const confirmLogout = () => { logout(); notify({ message: 'Logged out successfully', type: 'success' }); navigate('/login'); }; return <div className="security-page"><PageHeader /><div className="security-dashboard-grid"><main className="security-main-column"><EmailCard user={user} onUserUpdate={updateUser} /><PasswordCard password={password} setPassword={setPassword} /><DangerZoneCard onLogout={() => setLogoutOpen(true)} /></main><div className="security-side-column"><SecurityScoreCard password={password} /><SecurityTipsCard /><TwoFactorCard /></div></div><LogoutDialog open={logoutOpen} onClose={() => setLogoutOpen(false)} onConfirm={confirmLogout} /></div>; }
