export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  FORGOT_PASSWORD: '/forgot-password',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',
  PROFILE: '/profile',
  CREATOR: '/creator',
  CREATOR_HOME: '/creator/home',
  CREATOR_PROFILE: '/creator/profile',
  CREATOR_CAMPAIGNS: '/creator/campaigns',
  CREATOR_MY_CAMPAIGNS: '/creator/my-campaigns',
  CREATOR_APPLICATIONS: '/creator/applications',
  CREATOR_ANALYTICS: '/creator/analytics',
  CREATOR_SECURITY: '/creator/security',
  BRAND: '/brand',
  BRAND_HOME: '/brand/home',
  CAMPAIGNS: '/campaigns',
  BRAND_CAMPAIGNS: '/brand/campaigns',
  BRAND_CAMPAIGN_CREATE: '/brand/campaigns/create',
  BRAND_CAMPAIGN_DETAILS: '/brand/campaigns/:campaignId',
  BRAND_CAMPAIGN_EDIT: '/brand/campaigns/:campaignId/edit',
  SETTINGS: '/settings',
};
