import { useContext, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import useAuth from '../../hooks/useAuth.js';
import { NotificationContext } from '../../context/NotificationContext.jsx';
import { userService } from '../../services/userService.js';
import './BrandSecurityPage.css';

const PasswordIcon = () => <svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="4" y="10" width="16" height="10" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/><path d="M12 14v2"/></svg>;
const MailIcon = () => <svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 5h18v14H3z"/><path d="m3 7 9 6 9-6"/></svg>;
const ShieldIcon = () => <svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/><path d="m9 12 2 2 4-4"/></svg>;
const ExitIcon = () => <svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m10 17 5-5-5-5"/><path d="M15 12H3"/><path d="M14 4h4a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2h-4"/></svg>;

export function BrandSecurityHeader() { return <header className="brand-security-header"><h1>Security</h1><p>Manage your account security and credentials.</p></header>; }
export function BrandSecurityScore({ newPassword }) { const score = [newPassword.length >= 8, /[A-Z]/.test(newPassword), /[a-z]/.test(newPassword), /\d/.test(newPassword), /[^A-Za-z0-9]/.test(newPassword)].filter(Boolean).length; const status = score === 5 ? 'Strong' : score >= 3 ? 'Medium' : 'Weak'; return <section className="brand-security-score"><div><span className="brand-security-icon"><ShieldIcon /></span><p>Security Score</p></div><strong className={status.toLowerCase()}>{status}</strong><span className="brand-security-score-bar"><i style={{ width: `${Math.max(20, score * 20)}%` }} /></span><small>{newPassword ? 'Based on your new password.' : 'Use a strong password to improve your score.'}</small></section>; }
export function BrandSecurityTips() { return <section className="brand-security-tips"><div><span className="brand-security-icon">✦</span><h2>Security Tips</h2></div><ul><li>Use a strong, unique password.</li><li>Keep your recovery email updated.</li><li>Enable 2FA when it becomes available.</li></ul></section>; }

export function BrandEmailCard() {
  const { user, updateUser } = useAuth(); const { notify } = useContext(NotificationContext); const [open, setOpen] = useState(false); const [newEmail, setNewEmail] = useState(''); const [code, setCode] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const reset = () => { setOpen(false); setNewEmail(''); setCode(''); setError(''); };
  const sendCode = () => { if (!/\S+@\S+\.\S+/.test(newEmail)) return setError('Enter a valid new email address first.'); setError(''); notify({ message: 'Verification code requested', type: 'success' }); };
  const updateEmail = async (event) => { event.preventDefault(); if (!/\S+@\S+\.\S+/.test(newEmail)) return setError('Enter a valid new email address.'); if (!code.trim()) return setError('Enter the verification code.'); setBusy(true); setError(''); try { const updated = await userService.updateProfile({ name: user?.name || user?.fullName || '', email: newEmail, role: user?.role || 'BRAND' }); updateUser(updated); notify({ message: 'Email updated successfully', type: 'success' }); reset(); } catch (err) { setError(err.response?.data?.message || 'Unable to update email. Please try again.'); notify({ message: 'Email update failed', type: 'error' }); } finally { setBusy(false); } };
  return <section className="brand-security-card"><div className="brand-security-card-title"><span className="brand-security-icon"><MailIcon /></span><div><h2>Email Information</h2><p>Use an up-to-date email for account access and team updates.</p></div></div><div className="brand-email-summary"><div><span>Current Email</span><strong>{user?.email || 'Not available'}</strong></div><button className="brand-security-outline" type="button" onClick={() => setOpen(!open)}>{open ? 'Close' : 'Change Email'}</button></div><div className={`brand-email-collapse ${open ? 'open' : ''}`}>{open && <form onSubmit={updateEmail}><div className="brand-email-fields"><label>Current Email<input className="f-input" value={user?.email || ''} readOnly /></label><label>New Email<input className="f-input" type="email" value={newEmail} onChange={(e) => setNewEmail(e.target.value)} placeholder="name@company.com" disabled={busy} /></label></div><div className="brand-code-field"><label>Verification Code<input className="f-input" value={code} onChange={(e) => setCode(e.target.value)} placeholder="Enter verification code" disabled={busy} /></label><button type="button" className="brand-security-outline" onClick={sendCode} disabled={busy}>Send Code</button></div>{error && <span className="err-msg">{error}</span>}<div className="brand-security-actions"><button type="button" className="btn-back" onClick={reset} disabled={busy}>Cancel</button><button type="submit" className="brand-security-primary" disabled={busy}>{busy ? <span className="spin" /> : 'Update Email'}</button></div></form>}</div></section>;
}

function BrandPasswordField({ id, label, value, onChange, error, busy }) { const [visible, setVisible] = useState(false); return <label className="brand-password-field">{label}<span><input id={id} className={`f-input ${error ? 'err' : ''}`} type={visible ? 'text' : 'password'} value={value} onChange={onChange} disabled={busy} autoComplete={id === 'brand-current-password' ? 'current-password' : 'new-password'} /><button type="button" onClick={() => setVisible(!visible)} aria-label={`${visible ? 'Hide' : 'Show'} ${label}`}>{visible ? 'Hide' : 'Show'}</button></span>{error && <em>{error}</em>}</label>; }
export function BrandPasswordCard({ password, setPassword }) {
  const { notify } = useContext(NotificationContext); const [busy, setBusy] = useState(false); const [errors, setErrors] = useState({}); const [apiError, setApiError] = useState(''); const checks = useMemo(() => ({ length: password.newPassword.length >= 8, uppercase: /[A-Z]/.test(password.newPassword), lowercase: /[a-z]/.test(password.newPassword), number: /\d/.test(password.newPassword), special: /[^A-Za-z0-9]/.test(password.newPassword) }), [password.newPassword]);
  const save = async (event) => { event.preventDefault(); const next = {}; if (!password.currentPassword) next.current = 'Current password is required.'; if (!checks.length) next.next = 'Use at least 8 characters.'; else if (!Object.values(checks).every(Boolean)) next.next = 'Meet every password requirement.'; if (password.newPassword !== password.confirmPassword) next.confirm = 'Passwords do not match.'; setErrors(next); setApiError(''); if (Object.keys(next).length) return; setBusy(true); try { await userService.changePassword(password); setPassword({ currentPassword: '', newPassword: '', confirmPassword: '' }); notify({ message: 'Password updated successfully', type: 'success' }); } catch (err) { setApiError(err.response?.data?.message || 'Password update failed. Verify your current password.'); notify({ message: 'Password change failed', type: 'error' }); } finally { setBusy(false); } };
  const change = (key) => (event) => setPassword({ ...password, [key]: event.target.value }); const labels = [['length', 'Minimum 8 characters'], ['uppercase', 'Uppercase letter'], ['lowercase', 'Lowercase letter'], ['number', 'Number'], ['special', 'Special character']];
  return <section className="brand-security-card"><div className="brand-security-card-title"><span className="brand-security-icon"><PasswordIcon /></span><div><h2>Password</h2><p>Keep your brand account secure with a strong, unique password.</p></div></div>{apiError && <div className="brand-security-error">{apiError}</div>}<form className="brand-password-layout" onSubmit={save}><div><BrandPasswordField id="brand-current-password" label="Current Password" value={password.currentPassword} onChange={change('currentPassword')} error={errors.current} busy={busy} /><BrandPasswordField id="brand-new-password" label="New Password" value={password.newPassword} onChange={change('newPassword')} error={errors.next} busy={busy} /><BrandPasswordField id="brand-confirm-password" label="Confirm Password" value={password.confirmPassword} onChange={change('confirmPassword')} error={errors.confirm} busy={busy} /></div><div className="brand-password-rules"><h3>Password Requirements</h3>{labels.map(([key, label]) => <p key={key} className={checks[key] ? 'complete' : ''}><b>{checks[key] ? '✓' : '•'}</b>{label}</p>)}</div><button className="brand-security-primary brand-password-submit" type="submit" disabled={busy}>{busy ? <span className="spin" /> : 'Update Password'}</button></form></section>;
}
export function BrandTwoFactorCard() { return <section className="brand-security-card brand-two-factor"><span>Coming Soon</span><h2>Two-Factor Authentication</h2><p>Two-factor authentication will be available in a future release, adding another layer of protection to your Brand account.</p></section>; }
export function BrandDangerZone({ onLogout }) { return <section className="brand-security-card brand-danger-zone"><div className="brand-security-card-title"><span className="brand-security-icon"><ExitIcon /></span><div><h2>Danger Zone</h2><p>Actions that affect your current Brand account session.</p></div></div><div><div><h3>Logout</h3><p>You will need to sign in again to access your Brand account.</p></div><button type="button" className="brand-danger-button" onClick={onLogout}>Logout</button></div></section>; }
export function BrandLogoutDialog({ open, onClose, onConfirm }) { if (!open) return null; return <div className="brand-logout-backdrop"><div className="brand-logout-dialog" role="dialog" aria-modal="true" aria-labelledby="brand-logout-title"><span className="brand-logout-icon"><ExitIcon /></span><h2 id="brand-logout-title">Logout?</h2><p>You will need to sign in again to access your Brand account.</p><div><button type="button" className="btn-back" onClick={onClose}>Cancel</button><button type="button" className="brand-danger-button" onClick={onConfirm}>Logout</button></div></div></div>; }

export default function BrandSecurityPage() { const { logout } = useAuth(); const { notify } = useContext(NotificationContext); const navigate = useNavigate(); const [password, setPassword] = useState({ currentPassword: '', newPassword: '', confirmPassword: '' }); const [logoutOpen, setLogoutOpen] = useState(false); const finishLogout = () => { logout(); notify({ message: 'Logged out successfully', type: 'success' }); navigate('/login'); }; return <div className="brand-security-page"><BrandSecurityHeader /><div className="brand-security-grid"><main><BrandEmailCard /><BrandPasswordCard password={password} setPassword={setPassword} /><BrandDangerZone onLogout={() => setLogoutOpen(true)} /></main><aside><BrandSecurityScore newPassword={password.newPassword} /><BrandSecurityTips /><BrandTwoFactorCard /></aside></div><BrandLogoutDialog open={logoutOpen} onClose={() => setLogoutOpen(false)} onConfirm={finishLogout} /></div>; }
