import { useContext, useState } from 'react';
import useAuth from '../../hooks/useAuth.js';
import { brandService } from '../../services/brandService.js';
import { NotificationContext } from '../../context/NotificationContext.jsx';
import './BrandProfile.css';

const INDUSTRIES = [{ value: 'TECHNOLOGY', label: 'Technology' }, { value: 'ENTERTAINMENT', label: 'Entertainment' }, { value: 'HEALTHCARE', label: 'Healthcare' }, { value: 'GAMING', label: 'Gaming' }, { value: 'LIFESTYLE', label: 'Lifestyle' }, { value: 'FASHION', label: 'Fashion' }, { value: 'TRAVEL', label: 'Travel' }, { value: 'BEAUTY', label: 'Beauty' }, { value: 'FOOD', label: 'Food' }, { value: 'SPORTS', label: 'Sports' }, { value: 'EDUCATION', label: 'Education' }, { value: 'FINANCE', label: 'Finance' }, { value: 'OTHER', label: 'Other' }];
const COMPANY_SIZES = [{ value: 'STARTUP', label: 'Startup (1-10)' }, { value: 'SMALL', label: 'Small (11-50)' }, { value: 'MEDIUM', label: 'Medium (51-200)' }, { value: 'LARGE', label: 'Large (201-1000)' }, { value: 'ENTERPRISE', label: 'Enterprise (1000+)' }];
const Icon = ({ children }) => <svg width="18" height="18" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{children}</svg>;
const industryLabel = (value) => INDUSTRIES.find((item) => item.value === value)?.label || value || 'Not provided';
const sizeLabel = (value) => COMPANY_SIZES.find((item) => item.value === value)?.label || value || 'Not provided';
const locationLabel = (profile) => [profile?.city?.trim(), profile?.state?.trim()].filter(Boolean).join(', ') || 'Not provided';

export function BrandProfileHeader({ complete, editing, onEdit, onCancel, onSave, loading }) { return <header className="brand-profile-header"><div><div className="brand-profile-title-row"><h1>{editing ? 'Edit Brand Profile' : 'Brand Profile'}</h1><span className={`brand-profile-status ${complete ? 'complete' : ''}`}>{complete ? '✓ Profile Complete' : 'Profile Incomplete'}</span></div><p>Manage your brand information and account details.</p></div><div className="brand-profile-header-actions">{editing ? <><button type="button" className="btn-back" onClick={onCancel} disabled={loading}>Cancel</button><button type="button" className="brand-profile-primary" onClick={onSave} disabled={loading}>{loading ? <span className="spin" /> : 'Save Changes'}</button></> : <button type="button" className="brand-profile-primary" onClick={onEdit}>Edit Profile</button>}</div></header>; }

export function CompanyInfoCard({ profile }) { const name = profile.companyName || 'Brand'; const logo = profile.logoUrl || profile.logo || profile.companyLogoUrl; return <section className="brand-profile-card brand-company-info"><p className="brand-profile-eyebrow">Company Information</p><div className="brand-company-summary"><div className="brand-company-avatar">{logo ? <img src={logo} alt={`${name} logo`} /> : name.charAt(0).toUpperCase()}</div><div><span>Company Name</span><h2>{name}</h2><small><Icon><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/><path d="m9 12 2 2 4-4"/></Icon>Verified Brand</small></div></div></section>; }

function DetailIcon({ type }) { if (type === 'website') return <Icon><path d="M10 13a5 5 0 0 0 7.1.1l2-2a5 5 0 0 0-7.1-7.1l-1.1 1.1"/><path d="M14 11a5 5 0 0 0-7.1-.1l-2 2A5 5 0 0 0 12 20l1.1-1.1"/></Icon>; if (type === 'industry') return <Icon><path d="M3 21h18"/><path d="M5 21V7l7-4 7 4v14"/><path d="M9 21v-5h6v5M8 10h.01M16 10h.01"/></Icon>; if (type === 'size') return <Icon><path d="M4 21V5h12v16M16 9h4v12M8 9h4M8 13h4M8 17h4"/></Icon>; return <Icon><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2"/></Icon>; }
export function CompanyDetailsGrid({ profile }) { const details = [{ type: 'website', title: 'Website', value: profile.website }, { type: 'industry', title: 'Industry', value: industryLabel(profile.industry) }, { type: 'size', title: 'Company Size', value: sizeLabel(profile.companySize) }, { type: 'location', title: 'Location', value: locationLabel(profile) }]; return <section className="brand-profile-card brand-details-card"><h2>Company Details</h2><div className="brand-details-grid">{details.map((detail) => <div className="brand-detail" key={detail.title}><span className="brand-detail-icon"><DetailIcon type={detail.type} /></span><div><p>{detail.title}</p>{detail.type === 'website' && detail.value ? <a href={detail.value} target="_blank" rel="noopener noreferrer">{detail.value}<Icon><path d="M14 3h7v7"/><path d="M10 14 21 3"/><path d="M21 14v7H3V3h7"/></Icon></a> : <strong>{detail.value || 'Not provided'}</strong>}</div></div>)}</div></section>; }
export function BrandDescriptionCard({ description }) { return <section className="brand-profile-card brand-description-card"><div className="brand-description-heading"><span><Icon><path d="m12 3 2.8 5.7L21 9.6l-4.5 4.4 1.1 6.2-5.6-3-5.6 3 1.1-6.2L3 9.6l6.2-.9Z"/></Icon></span><div><h2>Description / About Brand</h2><p>Help creators understand your company and collaboration opportunities.</p></div></div><p className={description ? '' : 'empty'}>{description || 'Tell creators about your company, products, goals, and collaboration opportunities.'}</p></section>; }
function EditField({ label, children }) { return <label className="brand-edit-field"><span>{label}</span>{children}</label>; }
export function BrandProfileEditForm({ values, setValues }) { const change = (key) => (event) => setValues({ ...values, [key]: event.target.value }); return <div className="brand-profile-edit"><section className="brand-profile-card"><p className="brand-profile-eyebrow">Company Information</p><div className="brand-edit-grid"><EditField label="Company Name"><input className="f-input" value={values.companyName} onChange={change('companyName')} /></EditField><EditField label="Website"><input className="f-input" value={values.website} onChange={change('website')} /></EditField><EditField label="Industry"><select className="f-select" value={values.industry} onChange={change('industry')}><option value="">Select industry</option>{INDUSTRIES.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></EditField><EditField label="Company Size"><select className="f-select" value={values.companySize} onChange={change('companySize')}><option value="">Select size</option>{COMPANY_SIZES.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></EditField><EditField label="State"><input className="f-input" value={values.state} onChange={change('state')} /></EditField><EditField label="City"><input className="f-input" value={values.city} onChange={change('city')} /></EditField></div></section><section className="brand-profile-card"><EditField label="Description"><textarea className="f-textarea" value={values.description} onChange={change('description')} /></EditField></section></div>; }

export default function BrandProfile() {
  const { brandProfile, updateBrandProfile } = useAuth(); const { notify } = useContext(NotificationContext); const [isEditing, setIsEditing] = useState(false); const [values, setValues] = useState({}); const [loading, setLoading] = useState(false);
  if (!brandProfile) return null;
  const complete = Boolean(brandProfile.companyName && brandProfile.website && brandProfile.industry && brandProfile.companySize && brandProfile.city && brandProfile.state && brandProfile.description);
  const startEditing = () => { setValues({ companyName: brandProfile.companyName || '', website: brandProfile.website || '', industry: brandProfile.industry || '', companySize: brandProfile.companySize || '', city: brandProfile.city || '', state: brandProfile.state || '', description: brandProfile.description || '' }); setIsEditing(true); };
  const save = async () => { const checks = [['companyName', 'Company Name'], ['website', 'Website URL'], ['industry', 'Industry selection'], ['companySize', 'Company Size selection'], ['city', 'City'], ['state', 'State'], ['description', 'Description']]; const missing = checks.find(([key]) => !String(values[key] || '').trim()); if (missing) return notify({ message: `${missing[1]} is required`, type: 'error' }); const payload = { companyName: values.companyName.trim(), website: values.website.trim(), industry: values.industry, companySize: values.companySize, city: values.city.trim(), state: values.state.trim(), description: values.description.trim() }; setLoading(true); try { const saved = await brandService.updateBrandProfile(payload); updateBrandProfile(saved); setIsEditing(false); notify({ message: 'Changes saved successfully!', type: 'success' }); } catch (err) { notify({ message: err.response?.data?.message || 'Failed to update brand profile.', type: 'error' }); } finally { setLoading(false); } };
  return <div className="brand-profile-page"><BrandProfileHeader complete={complete} editing={isEditing} onEdit={startEditing} onCancel={() => setIsEditing(false)} onSave={save} loading={loading} />{isEditing ? <BrandProfileEditForm values={values} setValues={setValues} /> : <><CompanyInfoCard profile={brandProfile} /><CompanyDetailsGrid profile={brandProfile} /><BrandDescriptionCard description={brandProfile.description} /></>}</div>;
}
