import { useCallback, useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { creatorService } from '../../services/creatorService.js';
import { campaignService } from '../../services/campaignService.js';
import './DiscoverCreatorsPage.css';

const list = data => Array.isArray(data) ? data : data?.content || data?.creators || [];
const id = c => c?.creatorId || c?.id || c?.userId;
const name = c => c?.displayName || c?.fullName || c?.name || 'Creator';
const niches = c => Array.isArray(c?.niches) ? c.niches : c?.niche ? [c.niche] : [];
const platforms = c => Array.isArray(c?.platforms) ? c.platforms : c?.platform ? [c.platform] : [];
const get = (c, ...keys) => keys.reduce((v, key) => v ?? c?.analytics?.analytics?.[key] ?? c?.analytics?.[key] ?? c?.[key], undefined);
const num = (c, ...keys) => Number(get(c, ...keys)) || 0;
const compact = n => n ? new Intl.NumberFormat('en-IN', { notation: 'compact', maximumFractionDigits: 1 }).format(n) : '—';

export default function DiscoverCreatorsPage() {
  const navigate = useNavigate();
  const [creators, setCreators] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [query, setQuery] = useState(''); const [niche, setNiche] = useState(''); const [minimum, setMinimum] = useState(''); const [sort, setSort] = useState('subscribers');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const profiles = list(await creatorService.getCreators()); const enriched = await Promise.all(profiles.map(async creator => { try { return id(creator) ? { ...creator, analytics: await campaignService.getCreatorAnalytics(id(creator)) } : creator; } catch { return creator; } })); setCreators(enriched); } catch (err) { setError(err?.response?.data?.message || 'Unable to load creators.'); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const nicheOptions = useMemo(() => [...new Set(creators.flatMap(niches))].sort(), [creators]);
  const results = useMemo(() => creators.filter(c => `${name(c)} ${get(c, 'channelName', 'channelTitle') || ''}`.toLowerCase().includes(query.toLowerCase()) && (!niche || niches(c).some(n => n.toLowerCase() === niche.toLowerCase())) && (!minimum || num(c, 'subscriberCount', 'subscribers') >= Number(minimum))).sort((a, b) => num(b, ...(sort === 'views' ? ['totalViews', 'viewCount'] : sort === 'engagement' ? ['engagementRate'] : ['subscriberCount', 'subscribers'])) - num(a, ...(sort === 'views' ? ['totalViews', 'viewCount'] : sort === 'engagement' ? ['engagementRate'] : ['subscriberCount', 'subscribers']))), [creators, query, niche, minimum, sort]);
  const clear = () => { setQuery(''); setNiche(''); setMinimum(''); setSort('subscribers'); };
  return <section className="discover-creators"><header className="discover-heading"><span>CREATOR DISCOVERY</span><h1>Find the right <em>creators.</em></h1><p>Discover high-performing creators, explore their audience and analytics, and find the right fit for your next campaign.</p><small>{loading ? 'Loading creators…' : `${creators.length} creators available`}</small></header><div className="discover-toolbar"><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search creators or channels" /><select value={niche} onChange={e => setNiche(e.target.value)}><option value="">All niches</option>{nicheOptions.map(n => <option key={n}>{n}</option>)}</select><select value={minimum} onChange={e => setMinimum(e.target.value)}><option value="">Any audience</option><option value="1000">1K+ subscribers</option><option value="10000">10K+ subscribers</option><option value="50000">50K+ subscribers</option><option value="100000">100K+ subscribers</option></select><select value={sort} onChange={e => setSort(e.target.value)}><option value="subscribers">Top creators</option><option value="views">Most views</option><option value="engagement">Highest engagement</option></select><button onClick={clear}>Clear filters</button></div>{loading ? <div className="discover-skeletons">{[1, 2, 3, 4].map(x => <div key={x} />)}</div> : error ? <div className="discover-state"><h2>Unable to load creators.</h2><p>{error}</p><button onClick={load}>Try again</button></div> : !results.length ? <div className="discover-state"><h2>No creators found</h2><p>Try changing your filters or search.</p><button onClick={clear}>Clear filters</button></div> : <div className="creator-leaderboard">{results.map((c, index) => <article className={`leaderboard-row rank-${index < 3 ? index + 1 : 'other'}`} key={id(c) || index}><b className="creator-rank">#{index + 1}</b><div className="creator-discovery-avatar">{name(c).charAt(0)}</div><div className="creator-identity"><strong>{name(c)}</strong><span>{get(c, 'channelName', 'channelTitle') || '—'}</span></div><div className="creator-niches">{niches(c).slice(0, 2).map(n => <span key={n}>{n}</span>)}</div><div className="creator-metric"><span>Subscribers</span><strong>{compact(num(c, 'subscriberCount', 'subscribers'))}</strong></div><div className="creator-metric"><span>Total views</span><strong>{compact(num(c, 'totalViews', 'viewCount'))}</strong></div><div className="creator-metric engagement"><span>Engagement</span><strong>{get(c, 'engagementRate') ?? '—'}{get(c, 'engagementRate') !== undefined ? '%' : ''}</strong></div><button className="discover-view" onClick={() => navigate(`/brand/creators/${id(c)}/analytics`)} disabled={!id(c)}>View Analytics</button></article>)}</div>}</section>;
}
